console.log(42);
console.log("foobar");
console.log("a string with numbers (e.g., 42) and quotes (e.g., '' and \"\")");
console.log(abc);
console.log(true);
console.log(false);
console.log(3 + 4);
console.log(3 - 4);
console.log(3 * 4);
console.log(3 / 4);
console.log(5 == 6);
console.log(5 != 6);
console.log(5 < 6);
console.log(5 <= 6);
console.log(5 > 6);
console.log(5 >= 6);
console.log(7 == 0);