// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

function unannotate(x) {
  return x.it;
}

function indent(s, i) {
  var pad = Js_string.repeat(i, " ");
  return Js_string.replaceByRe(/\n/g, "\n" + pad, s);
}

var Impossible = /* @__PURE__ */Caml_exceptions.create("Format.Impossible");

export {
  unannotate ,
  indent ,
  Impossible ,
}
/* No side effect */
